on:
  workflow_dispatch:
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm install -g yarn
      - run: yarn
      - run: yarn build
      - run: yarn test
      - run: yarn test:e2e
      - uses: dorny/test-reporter@v1
        if: always()   # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: reports/jest-*.xml    # Path to test results
          reporter: jest-junit        # Format of test results
